name: Flight Hunter

on:
  workflow_dispatch:
  schedule:
    - cron: "0 */6 * * *"

jobs:
  check-flight:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Setup Python
        uses: actions/setup-python@v6
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          playwright install chromium

      - name: Run flight checker
        run: |
          python flight_checker.py

      - name: Upload screenshots
        uses: actions/upload-artifact@v4
        with:
          name: flight-screenshots
          path: screenshots/
