name: Flight Check

on:
  workflow_dispatch:

jobs:
  check-flight:
    runs-on: ubuntu-latest

    steps:
      - name: Download repository
        uses: actions/checkout@v5

      - name: Setup Python
        uses: actions/setup-python@v6
        with:
          python-version: "3.12"

      - name: Install packages
        run: |
          pip install -r requirements.txt
          playwright install chromium

      - name: Run flight checker
        run: python flight_checker.py
